# Generated by Django 5.2 on 2026-04-27 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(max_length=2000, upload_to=''),
        ),
    ]
